### ISSUE TITLE
Repeated "hold" events for level tiles only - single event only for button tiles 

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-TouchPanel-WEB-APP#1]
E.g. if I have a simple button (on/off) tile I don't want repeated "hold" events if I press + hold. I just want the one event.

Only want repeated "hold" events for level up/down tiles.

My bad - I missed this in the original spec for "hold" events!

**Comment by caitken-com** [comment]
Please pull & test!

**Comment by sumnerboy12** [comment]
Looks good - thanks @caitken-com!
