### ISSUE TITLE
buttonUpDown event is missing the 'state' property

### ISSUE THREAD

**Issue by kghxkgh** [OXRS-IO/OXRS-IO-TouchPanel-WEB-APP#2]
Event type "up" and "down" are missing the "state" property.
(It exists on the main button press.)

stat/TpEsp32 : msg.payload : Object
object
screen: 5
tile: 1
style: "buttonUpDown"
type: "down"
event: "single"

https://oxrs.io/docs/firmware/touch-panel-esp32.html#buttonupdown

**Comment by caitken-com** [comment]
As per docs, _state_ should only be present when the main button is pressed:

> The current tile state (prior to this event), only included for button press events

**Comment by kghxkgh** [comment]
You are observant with the fine print.

When I was coding the flow, I only wanted to process up/downs if the tile is On.
I can handle the tile state within the flow too.

I think there was some discussion in Discord regarding the topic relating to whether you can change the volume level when the tile is off. Could make for a surprise!

I just checked in the TP firmware and your behavior matches, so lets keep it like this.
Issue can be closed.
