### ISSUE TITLE
Possibility to make web ui URLs that work when refreshing or in shortcuts

### ISSUE THREAD

**Issue by kghxkgh** [OXRS-IO/OXRS-IO-TouchPanel-WEB-APP#5]
sumnerboy   25/4 at 6:53 AM
I'm finding it difficult to create a shortcut on my Android phone to the OXRS web app - I can enter https://touch.oxrs.io/ but I am immediately redirected to https://touch.oxrs.io/screen/1 (after entering creds the first time) - and creating a shortcut to /screen/1 doesn't work when I try to open it again - but I can't create a home screen shortcut until the page loads...
not a problem on my PC browser where I can manually edit the shortcut link

KeithH   25/4 at 8:06 AM
I'm also experiencing a difficulty with this when I want to refresh the browser I need to remove the suffix.

ChrisAitken  25/4 at 8:14 AM
Yeah. The issue is those URLs don’t exist before the JavaScript is fully loaded. Only index.html exists before hand.

**Comment by kghxkgh** [comment]
ChrisAitken  25/4 at 8:17 AM
If we have access the github pages’ rules engine might be able to write redirects to convert /screen/x to index.htm?screen=x 
I’m still hosting my version in NR because I can’t use https. So in NR I’ve got redirects doing that ^

ChrisAitken 25/4 at 8:42 AM
This might be the fix. Although I don’t full understand what it’s doing/ if it’ll work for us.
https://github.com/jekyll/jekyll-redirect-from

**Comment by kghxkgh** [comment]
Workaround found for getting a URL link without the suffix.
One is available from the screen select page.
Works for creating a shortcut in Android.

**Comment by caitken-com** [comment]
There's no JS solution for this. After re-reading the Jekyll info it creates a html per possible URL. Not something I really wanna add to the hosting requirements of this SPA.

**Comment by caitken-com** [comment]
@kghxkgh, I forgot to mention there's a URL param you can set to deep link to screen on page load:
`index.html?screen=X` _X being screen ID_.
Eg: `https://touch.oxrs.io/?screen=2`

Here's documentation on how to edit a bookmark on Android:
<https://support.google.com/chrome/answer/188842?hl=en&co=GENIE.Platform%3DAndroid#zippy=%2Cedit-a-bookmark>

iOS just press-hold on the bookmark icon to edit its URL.
