### ISSUE TITLE
Footer alignment issue 

### ISSUE THREAD

**Issue by kghxkgh** [OXRS-IO/OXRS-IO-TouchPanel-WEB-APP#7]
25/4 10:12pm Realised the custom footers were broken. (unsure of details.)

Footer alignment issue. Left custom text should be 'middle' aligned. (possibly center&right text too)

![image](https://user-images.githubusercontent.com/74844260/234399271-06069d78-3f70-4c8a-af43-44dc24f0578e.png)

**Comment by caitken-com** [comment]
Fix is now fixed.
