### ISSUE TITLE
Support for colored text in Footer

### ISSUE THREAD

**Issue by kghxkgh** [OXRS-IO/OXRS-IO-TouchPanel-WEB-APP#9]
Documented here:  (See Tip at the end of the section.)
https://oxrs.io/docs/firmware/touch-panel-esp32.html#set-footer

Example:
{
  "screens":[
    {
      "screen": 1,
      "footer":{
        "left": "#FF0000 " &  " red text #", 
        "center": "#FF0000 "  & "text #",
        "right": ""
      }
    }
  ]
}

**Comment by caitken-com** [comment]
This now works
